/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Conversation = IDL.Record({
  'title' : IDL.Text,
  'lastMessageTimestamp' : IDL.Int,
  'messages' : IDL.Vec(Message),
});

export const idlService = IDL.Service({
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteConversation' : IDL.Func([IDL.Nat], [], []),
  'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
  'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Conversation = IDL.Record({
    'title' : IDL.Text,
    'lastMessageTimestamp' : IDL.Int,
    'messages' : IDL.Vec(Message),
  });
  
  return IDL.Service({
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteConversation' : IDL.Func([IDL.Nat], [], []),
    'getAllConversations' : IDL.Func([], [IDL.Vec(Conversation)], ['query']),
    'getConversation' : IDL.Func([IDL.Nat], [Conversation], ['query']),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };